name: Pages CI/CD

on:
  push:
    branches:
    - main
  pull_request:

  permissions:
    contents: write
    pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '$GITHUB_WORKSPACE/scripts'
          
      - name: Build
        id: build
        run: |
          dir=$(mktemp -d)
          "$GITHUB_WORKSPACE"/scripts/build.sh "$dir"
          echo "dir=$dir" >> "$GITHUB_ENV"
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        with:
          cname: web.vytrac.me
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "$dir"
          commit_message: ${{ github.event.head_commit.message }}
